[package]
name = "channel_physics"
version = "0.1.0"
edition = "2021"
authors = ["MinuteModem"]

[lib]
name = "channel_physics"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37"
rand = "0.8"
rand_chacha = "0.3"
lazy_static = "1.4"

[profile.release]
lto = true